server:
    port: 8001
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
spring:
    application:
        name: demo-sec
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://127.0.0.1:3306/demodb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
    jpa:
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update